-- GENERATED by scripts/gen-ui-strings-seed.mjs from src/lib/i18n/defaults/*.json. Do not edit.
insert into public.ui_strings (key, value) values
  ('footer.rights', '{"ar":"جميع الحقوق محفوظة","en":"All rights reserved"}'),
  ('home.features.activities.body', '{"ar":"كل نشاط مع ألبوم صوره الخاص.","en":"Every activity with its own photo album."}'),
  ('home.features.activities.title', '{"ar":"الأنشطة","en":"Activities"}'),
  ('home.features.events.body', '{"ar":"مشاركاتنا في الفعاليات والمؤتمرات، مع التاريخ والمكان.","en":"Our participation in events and conferences, with date and location."}'),
  ('home.features.events.title', '{"ar":"دعوات ومؤتمرات","en":"Invitations & conferences"}'),
  ('home.features.sectors.body', '{"ar":"المحتوى منظم حسب القطاع: الزراعي، السياحي، البيئي، الصحي، التربوي وغيرها.","en":"Content organized by sector: agriculture, tourism, environment, health, education and more."}'),
  ('home.features.sectors.title', '{"ar":"القطاعات","en":"Sectors"}'),
  ('home.features.title', '{"ar":"ما الذي ستجده هنا","en":"What you''ll find here"}'),
  ('home.hero.badge', '{"ar":"الموقع قيد الإنشاء","en":"Site under construction"}'),
  ('home.hero.body', '{"ar":"هذه نسخة تجريبية من الموقع. سيتمكن فريق الجمعية قريبًا من نشر الأنشطة وألبومات الصور والمشاركات في الدعوات والمؤتمرات، وتعديل شكل الموقع بالكامل من لوحة تحكم بسيطة.","en":"This is a preview build. Soon the team will be able to publish activities with photo albums and participation in invitations and conferences, and restyle the whole site from a simple admin panel."}'),
  ('home.hero.cta', '{"ar":"اكتشف المزيد","en":"Learn more"}'),
  ('home.hero.title', '{"ar":"نعمل في الزراعة والبيئة والصحة والتعليم وحقوق المرأة والطفل","en":"Working in agriculture, the environment, health, education, and women''s & children''s rights"}'),
  ('nav.language', '{"ar":"اللغة","en":"Language"}'),
  ('nav.skip_to_content', '{"ar":"انتقل إلى المحتوى","en":"Skip to content"}'),
  ('site.name', '{"ar":"اسم الجمعية","en":"Organization Name"}'),
  ('site.tagline', '{"ar":"معًا من أجل تنمية مستدامة لمجتمعاتنا","en":"Together for the sustainable development of our communities"}')
on conflict (key) do update set value = excluded.value;
