-- Content: media library, sectors, objectives, posts (+ albums, sector links), pages.

-- Slugs are generated by the admin ("رابط الصفحة"): lowercase ASCII kebab-case.
create domain public.slug as text
  check (value ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(value) <= 120);

-- ---------------------------------------------------------------------------
-- Media library
-- ---------------------------------------------------------------------------
create table public.media (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  url text not null,
  width int check (width > 0),
  height int check (height > 0),
  size_bytes bigint check (size_bytes >= 0),
  alt public.i18n not null default '{}',
  uploaded_by uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger media_updated_at before update on public.media
  for each row execute function public.set_updated_at();

alter table public.media enable row level security;

create policy "media: public read" on public.media
  for select to anon, authenticated using (true);
create policy "media: editor insert" on public.media
  for insert to authenticated with check (public.is_editor());
create policy "media: editor update" on public.media
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "media: editor delete" on public.media
  for delete to authenticated using (public.is_editor());

-- ---------------------------------------------------------------------------
-- Sectors (القطاعات)
-- ---------------------------------------------------------------------------
create table public.sectors (
  id uuid primary key default gen_random_uuid(),
  slug public.slug not null unique,
  name public.i18n not null default '{}',
  description public.i18n not null default '{}',
  icon text,
  cover_image text,
  color text check (color is null or color ~ '^#[0-9A-Fa-f]{6}$'),
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger sectors_updated_at before update on public.sectors
  for each row execute function public.set_updated_at();

alter table public.sectors enable row level security;

create policy "sectors: read active" on public.sectors
  for select to anon, authenticated using (is_active or public.is_staff());
create policy "sectors: editor insert" on public.sectors
  for insert to authenticated with check (public.is_editor());
create policy "sectors: editor update" on public.sectors
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "sectors: editor delete" on public.sectors
  for delete to authenticated using (public.is_editor());

-- ---------------------------------------------------------------------------
-- Objectives (أهدافنا)
-- ---------------------------------------------------------------------------
create table public.objectives (
  id uuid primary key default gen_random_uuid(),
  text public.i18n not null default '{}',
  icon text,
  sector_id uuid references public.sectors (id) on delete set null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index objectives_sector_idx on public.objectives (sector_id);

create trigger objectives_updated_at before update on public.objectives
  for each row execute function public.set_updated_at();

alter table public.objectives enable row level security;

create policy "objectives: read active" on public.objectives
  for select to anon, authenticated using (is_active or public.is_staff());
create policy "objectives: editor insert" on public.objectives
  for insert to authenticated with check (public.is_editor());
create policy "objectives: editor update" on public.objectives
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "objectives: editor delete" on public.objectives
  for delete to authenticated using (public.is_editor());

-- ---------------------------------------------------------------------------
-- Posts: activity = نشاط, event = دعوات ومؤتمرات, news = خبر عام
-- ---------------------------------------------------------------------------
create type public.post_kind as enum ('activity', 'event', 'news');

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  kind public.post_kind not null default 'activity',
  slug public.slug not null unique,
  title public.i18n not null default '{}',
  excerpt public.i18n not null default '{}',
  body public.i18n not null default '{}',  -- Tiptap JSON per locale
  cover_media_id uuid references public.media (id) on delete set null,
  event_date date,
  location public.i18n,
  status public.content_status not null default 'draft',
  published_at timestamptz,
  is_featured boolean not null default false,
  author_id uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index posts_listing_idx on public.posts (kind, status, published_at desc);
create index posts_event_date_idx on public.posts (event_date desc) where kind = 'event';

create trigger posts_updated_at before update on public.posts
  for each row execute function public.set_updated_at();

-- Stamp published_at the first time a post is published.
create function public.set_published_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'published' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

create trigger posts_published_at before insert or update of status on public.posts
  for each row execute function public.set_published_at();

-- Is this post visible to the public? (Used by the album / sector-link policies.)
create function public.is_post_public(p_post_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.posts p
    where p.id = p_post_id and p.status = 'published' and p.published_at <= now()
  );
$$;

alter table public.posts enable row level security;

create policy "posts: read published" on public.posts
  for select to anon, authenticated
  using ((status = 'published' and published_at <= now()) or public.is_staff());
create policy "posts: editor insert" on public.posts
  for insert to authenticated with check (public.is_editor());
create policy "posts: editor update" on public.posts
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "posts: editor delete" on public.posts
  for delete to authenticated using (public.is_editor());

-- Optional many-to-many: a post may belong to no sector at all.
create table public.post_sectors (
  post_id uuid not null references public.posts (id) on delete cascade,
  sector_id uuid not null references public.sectors (id) on delete cascade,
  primary key (post_id, sector_id)
);

create index post_sectors_sector_idx on public.post_sectors (sector_id);

alter table public.post_sectors enable row level security;

create policy "post_sectors: read published" on public.post_sectors
  for select to anon, authenticated using (public.is_post_public(post_id) or public.is_staff());
create policy "post_sectors: editor insert" on public.post_sectors
  for insert to authenticated with check (public.is_editor());
create policy "post_sectors: editor update" on public.post_sectors
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "post_sectors: editor delete" on public.post_sectors
  for delete to authenticated using (public.is_editor());

-- The album: ordered photos with a caption each.
create table public.post_media (
  post_id uuid not null references public.posts (id) on delete cascade,
  media_id uuid not null references public.media (id) on delete restrict,
  sort_order int not null default 0,
  caption public.i18n not null default '{}',
  primary key (post_id, media_id)
);

create index post_media_order_idx on public.post_media (post_id, sort_order);
create index post_media_media_idx on public.post_media (media_id);

alter table public.post_media enable row level security;

create policy "post_media: read published" on public.post_media
  for select to anon, authenticated using (public.is_post_public(post_id) or public.is_staff());
create policy "post_media: editor insert" on public.post_media
  for insert to authenticated with check (public.is_editor());
create policy "post_media: editor update" on public.post_media
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "post_media: editor delete" on public.post_media
  for delete to authenticated using (public.is_editor());

-- ---------------------------------------------------------------------------
-- Custom pages (About, Who we are, Board…)
-- ---------------------------------------------------------------------------
create table public.pages (
  id uuid primary key default gen_random_uuid(),
  slug public.slug not null unique,
  title public.i18n not null default '{}',
  body public.i18n not null default '{}',  -- Tiptap JSON per locale
  cover_image text,
  show_in_nav boolean not null default false,
  status public.content_status not null default 'draft',
  seo_description public.i18n not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger pages_updated_at before update on public.pages
  for each row execute function public.set_updated_at();

alter table public.pages enable row level security;

create policy "pages: read published" on public.pages
  for select to anon, authenticated using (status = 'published' or public.is_staff());
create policy "pages: editor insert" on public.pages
  for insert to authenticated with check (public.is_editor());
create policy "pages: editor update" on public.pages
  for update to authenticated using (public.is_editor()) with check (public.is_editor());
create policy "pages: editor delete" on public.pages
  for delete to authenticated using (public.is_editor());
